---
version: "3.4"

services:
  etherpad:
    build:
      context: .
      dockerfile: Dockerfile
    image: etherpad:v1
          
    ports:
       - "8080:8080"
    networks:
      - etherpad-net
        #volumes:
        #- etherpad_data:/etherpad
    
  postgresql:
    restart: always
    image: postgres:9.6
    container_name: "database"
    environment:
      POSTGRES_DB: etherpad
      POSTGRES_USER: etherpad
      POSTGRES_PASSWORD: pass
    networks:
      - etherpad-net

networks:
  etherpad-net:

          #volumes:
          #etherpad_data:
